import type { ReportSchema } from "../../api/reports";

const AAPL_REPORT: ReportSchema = {
  schema_version: "2.0",
  department: "earnings_update",
  generated_at: new Date().toISOString(),
  page_furniture: {
    header: { left: "OpenLIA", right: "Earnings Update" },
    footer: {
      left: "Generated for internal use",
      center: "Page {page} of {total}",
      right: "AAPL · Q2 FY26",
    },
    disclaimer:
      "This report is generated by LIA from public filings and the live earnings call. It is not investment advice. Verify all figures against the company's primary disclosures before acting.",
  },
  cover: {
    title: "Apple Inc. — Q2 FY26 Earnings Update",
    subtitle: "Beat on Services, in-line on iPhone",
    eyebrow: "EARNINGS UPDATE · Q2 FY26 · POSTED 16:30 ET",
    ticker: "AAPL",
    tagline:
      "Services reaccelerated to +15.2% with structurally higher gross margin, offsetting flat iPhone units. Q3 guide implies the Street stays put.",
    tldr_label: "TL;DR",
    tldr: [
      "Revenue $94.2B (+5.4% y/y), $0.6B above Street; EPS $1.78 beats by $0.06.",
      "Services grew +15.2% to $26.8B — fastest pace in 7 quarters; segment gross margin held at 74.1%.",
      "iPhone $45.9B was in-line; units flat as China softness offset India and emerging-market strength.",
      "Buyback authorization raised by $110B; quarterly dividend +4% to $0.26.",
      "Q3 guide implies revenue +mid-single-digits y/y and gross margin 46.0–47.0% — modestly ahead of consensus midpoint.",
    ],
    key_metrics: [
      {
        label: "Revenue",
        value: "$94.2B",
        delta: "+5.4% y/y",
        delta_direction: "up",
        context: "Beat by $0.6B",
        tag: { label: "Beat", tone: "positive" },
        highlight: true,
      },
      {
        label: "EPS (diluted)",
        value: "$1.78",
        delta: "+8.5% y/y",
        delta_direction: "up",
        context: "Beat by $0.06",
        tag: { label: "Beat", tone: "positive" },
      },
      {
        label: "Gross margin",
        value: "47.1%",
        delta: "+90 bps y/y",
        delta_direction: "up",
        context: "Above guide high-end",
        tag: { label: "Beat", tone: "positive" },
      },
      {
        label: "Services revenue",
        value: "$26.8B",
        delta: "+15.2% y/y",
        delta_direction: "up",
        context: "Reaccelerated from +12.1%",
        tag: { label: "Inflection", tone: "positive" },
        highlight: true,
      },
    ],
  },
  rail: {
    verdict: {
      rating: "Buy",
      previous_rating: "Buy",
      target: "$245",
      upside: "+8.4%",
      as_of: "Post-print",
    },
    quick_stats: [
      { label: "Market cap", value: "$3.45T", context: "Pre-print" },
      { label: "AH move", value: "+1.65%", delta_direction: "up" },
      { label: "Lia signal", value: "82 / 100", context: "Confidence" },
      { label: "Latency", value: "3m 42s", context: "Wire to publish" },
    ],
    sparkline: {
      label: "AAPL · last 30d (close)",
      points: [
        { x: 0, y: 218.4 },
        { x: 1, y: 220.1 },
        { x: 2, y: 219.6 },
        { x: 3, y: 222.0 },
        { x: 4, y: 221.3 },
        { x: 5, y: 224.5 },
        { x: 6, y: 223.8 },
        { x: 7, y: 225.7 },
        { x: 8, y: 226.4 },
        { x: 9, y: 224.1 },
        { x: 10, y: 225.9 },
        { x: 11, y: 227.6 },
        { x: 12, y: 226.8 },
        { x: 13, y: 228.9 },
        { x: 14, y: 230.2 },
      ],
    },
  },
  sections: [
    {
      id: "verdict",
      title: "Verdict",
      blocks: [
        {
          type: "rating_badge",
          rating: "Buy · $245 PT (unchanged)",
          previous_rating: "Buy · $245 PT",
          change_date: "Post-print",
        },
        {
          type: "key_finding",
          content:
            "Maintain Buy. Services reaccelerating to +15% on a higher gross-margin base is the structurally important read; iPhone is the variable that will drive the next 12 months. Risk/reward is constructive at 27x NTM EPS given the buyback step-up.",
        },
        {
          type: "text",
          content:
            "The Q2 print clears the low bar set by the iPhone 16 cycle skeptics without changing the bull/bear debate. Services reaccelerated meaningfully — and importantly, the reacceleration was broad-based across App Store, advertising, and AppleCare, not just one line. Gross margin came in 90 bps better than the high-end of the guide on a richer Services mix and improved component costs. Capital returns were the headline surprise: an additional $110B authorization plus a 4% dividend bump. The Q3 guide is incrementally constructive — implies revenue growth slightly ahead of where consensus had drifted in the past two weeks.",
        },
      ],
    },
    {
      id: "the-print",
      title: "The Print",
      blocks: [
        {
          type: "metric_cards",
          metrics: [
            {
              label: "Revenue",
              value: "$94.2B",
              delta: "+5.4% y/y",
              delta_direction: "up",
              context: "Cons. $93.6B",
            },
            {
              label: "Gross margin",
              value: "47.1%",
              delta: "+90 bps y/y",
              delta_direction: "up",
              context: "Guide 46.0–47.0%",
            },
            {
              label: "Operating margin",
              value: "31.6%",
              delta: "+120 bps y/y",
              delta_direction: "up",
              context: "Cons. 30.7%",
            },
            {
              label: "EPS (diluted)",
              value: "$1.78",
              delta: "+8.5% y/y",
              delta_direction: "up",
              context: "Cons. $1.72",
            },
          ],
        },
        {
          type: "table",
          title: "Segment revenue",
          headers: [
            { key: "segment", label: "Segment", align: "left" },
            { key: "rev", label: "Revenue ($B)", align: "right" },
            { key: "yoy", label: "Y/Y", align: "right" },
            { key: "vs_cons", label: "vs Cons.", align: "right" },
            { key: "verdict", label: "Verdict", align: "left" },
          ],
          rows: [
            {
              segment: "iPhone",
              rev: "$45.9",
              yoy: "+0.5%",
              vs_cons: "−$0.3B",
              verdict: "In-line",
            },
            {
              segment: "Mac",
              rev: "$7.5",
              yoy: "+3.4%",
              vs_cons: "+$0.1B",
              verdict: "Beat",
            },
            {
              segment: "iPad",
              rev: "$6.4",
              yoy: "+15.0%",
              vs_cons: "+$0.4B",
              verdict: "Beat",
            },
            {
              segment: "Wearables / Home",
              rev: "$7.6",
              yoy: "−1.2%",
              vs_cons: "−$0.2B",
              verdict: "Light",
            },
            {
              segment: "Services",
              rev: "$26.8",
              yoy: "+15.2%",
              vs_cons: "+$0.6B",
              verdict: "Beat",
            },
          ],
          cell_format: {
            yoy: { rule: "directional" },
            vs_cons: { rule: "directional" },
            verdict: { rule: "tag-info" },
          },
          footnotes: [
            "Y/Y comparisons on reported basis. Constant-currency figures noted where management called them out.",
            "Consensus from Visible Alpha as of close prior to print.",
          ],
        },
        {
          type: "text",
          content:
            "iPhone of $45.9B was within $0.3B of consensus and grew +0.5% y/y — flat units against a tougher Greater China comp, partially offset by India/Indonesia where management cited record installed-base growth. Services drove most of the topline upside; Mac and iPad both beat on refreshed lineups (M3 Mac mini and iPad Air refresh shipped late in the quarter). Wearables remained the soft spot.",
        },
      ],
    },
    {
      id: "services",
      title: "Services Reaccelerates",
      blocks: [
        {
          type: "key_finding",
          content:
            "Services growth re-stepped from +12.1% last quarter to +15.2% this quarter — the fastest pace since FQ3'23 — with no single line dominating the contribution. App Store, advertising, AppleCare, and Cloud each grew double-digits.",
        },
        {
          type: "callout_grid",
          columns: 4,
          items: [
            {
              eyebrow: "App Store",
              title: "+13% y/y",
              description:
                "Re-acceleration driven by gaming and productivity; EU compliance changes had no material revenue impact in the quarter.",
            },
            {
              eyebrow: "Advertising",
              title: "+22% y/y",
              description:
                "Search ads on App Store and News inflected; Apple TV+ ad-supported tier still in early innings.",
            },
            {
              eyebrow: "AppleCare",
              title: "+11% y/y",
              description:
                "Tied to a richer Pro/Pro Max mix that drove higher attach rates; recurring revenue compounding.",
            },
            {
              eyebrow: "Cloud",
              title: "+17% y/y",
              description:
                "iCloud+ tiers continue to take share of paid storage; Apple Intelligence expected to be net-additive starting Q3.",
            },
          ],
        },
        {
          type: "text",
          content:
            "Crucially, Services gross margin held at 74.1% (vs 73.9% prior quarter) despite the higher mix of advertising and lower-margin lines — implying mix shift inside Services is favorable. We model Services to grow +14% in FY26, with upside from Apple Intelligence monetization not yet in numbers.",
        },
      ],
    },
    {
      id: "iphone",
      title: "iPhone & Hardware",
      blocks: [
        {
          type: "text",
          content:
            "iPhone units were essentially flat y/y. The geographic mix shift is the story: Greater China declined high-single-digits while India grew >40% and Indonesia inflected positive. Pro/Pro Max mix held above 60% of units, supporting ASP. Management was unusually explicit on the iPhone 17 cycle: Apple Intelligence rollout will be a multi-year tailwind, with the 17 cycle the first to fully benefit on a global basis.",
        },
        {
          type: "comparison_split",
          left: {
            title: "What worked",
            tone: "positive",
            items: [
              "Services reacceleration broad-based across 4 sub-lines.",
              "Gross margin 90 bps above the high end of guide.",
              "India installed base hit record; emerging markets +12% in aggregate.",
              "Mac/iPad refreshes drove +5% combined growth.",
              "Capital return: +$110B authorization, +4% dividend.",
            ],
          },
          right: {
            title: "What didn't",
            tone: "negative",
            items: [
              "Greater China iPhone revenue −7% y/y on local competition.",
              "Wearables −1.2% y/y; Vision Pro contribution still de minimis.",
              "FX a 1.2pt headwind to reported revenue this quarter.",
              "Channel inventory ticked up modestly into Q3.",
            ],
          },
        },
      ],
    },
    {
      id: "capital",
      title: "Capital Returns",
      blocks: [
        {
          type: "text",
          content:
            "Apple authorized an additional $110B for share repurchases, taking the cumulative authorization above $1.1T since 2012. The board also raised the quarterly dividend by 4% to $0.26 — Apple's 13th consecutive annual increase. Net cash position closed the quarter at $54B, with management reiterating the goal of net-cash neutral over time.",
        },
        {
          type: "key_finding",
          content:
            "The buyback step-up is the single most consequential update for next-twelve-month EPS — we lift FY26 EPS by ~$0.08 on a smaller share count, before any operating changes.",
        },
        {
          type: "table",
          title: "Capital returns trajectory",
          headers: [
            { key: "fy", label: "Fiscal year", align: "left" },
            { key: "buyback", label: "Buybacks ($B)", align: "right" },
            { key: "dividend", label: "Dividends ($B)", align: "right" },
            { key: "total", label: "Total ($B)", align: "right" },
            { key: "shares", label: "Diluted shares (B)", align: "right" },
          ],
          rows: [
            { fy: "FY23", buyback: "$77.6", dividend: "$15.0", total: "$92.6", shares: "15.81" },
            { fy: "FY24", buyback: "$95.4", dividend: "$15.2", total: "$110.6", shares: "15.46" },
            { fy: "FY25", buyback: "$104.3", dividend: "$15.7", total: "$120.0", shares: "15.18" },
            { fy: "FY26E", buyback: "$118.0", dividend: "$16.4", total: "$134.4", shares: "14.84" },
          ],
          footnotes: [
            "FY26E reflects the $110B incremental authorization announced this print.",
          ],
        },
      ],
    },
    {
      id: "guide",
      title: "Q3 Guide & Setup",
      blocks: [
        {
          type: "bullet_list",
          tone: "positive",
          items: [
            "Q3 revenue: management implied +mid-single-digits y/y growth (~$87–89B), modestly above the $87.4B consensus midpoint.",
            "Q3 gross margin guide: 46.0–47.0% — sequentially down on product mix but flat to slightly up y/y.",
            "Operating expenses: $14.3–14.5B; reflects continued AI/silicon R&D investment.",
            "Tax rate: 16.0% for the quarter; FY rate held at 16.5%.",
          ],
        },
        {
          type: "callout_grid",
          columns: 3,
          items: [
            {
              eyebrow: "Catalyst",
              title: "iPhone 17 launch — September",
              description:
                "Cycle setup constructive: Apple Intelligence broader rollout, A19 Pro, and the rumored slim variant could expand the upgrade pool.",
            },
            {
              eyebrow: "Catalyst",
              title: "Apple Intelligence — Q4 broader rollout",
              description:
                "Management framed AI as 'multi-year' and 'net-additive to Services.' First measurable financial impact expected in FY27.",
            },
            {
              eyebrow: "Watch",
              title: "China iPhone trajectory",
              description:
                "Local competition (Huawei in particular) and weak macro remain risk factors. Management cited stabilization but not recovery.",
            },
          ],
        },
      ],
    },
    {
      id: "risks",
      title: "Risks & Watch Items",
      blocks: [
        {
          type: "bullet_list",
          tone: "negative",
          items: [
            "China iPhone revenue: continued share loss to local OEMs would extend the −7% trajectory.",
            "Regulatory: EU Digital Markets Act compliance has been revenue-neutral so far; potential for incremental App Store fee dilution remains.",
            "Vision Pro: contribution remains immaterial; if the next-gen product fails to expand the addressable market, write-down risk is non-zero.",
            "FX: dollar strength has been a 1.2–1.5pt headwind for two consecutive quarters.",
            "Tariff exposure: management was asked but did not quantify potential pass-through impact.",
          ],
        },
      ],
    },
    {
      id: "call",
      title: "From the Call",
      blocks: [
        {
          type: "pull_quote",
          text:
            "Services revenue grew 15% to a new all-time record. We saw double-digit growth across all categories, and Services gross margin came in at 74%, an all-time high.",
          attribution: "Tim Cook",
          source: "CEO, prepared remarks",
          timestamp: "16:34 ET",
        },
        {
          type: "quote",
          text:
            "Our installed base of active devices reached a new all-time high across every product category and every geographic segment. India set an all-time revenue record; we are very pleased with that result.",
          speaker: "Tim Cook",
          role: "CEO",
          tag: { label: "Installed base", tone: "positive" },
          timestamp: "16:38 ET",
        },
        {
          type: "quote",
          text:
            "For the September quarter, we expect revenue to grow mid-single digits year-over-year. We expect gross margin to be between 46 and 47 percent.",
          speaker: "Luca Maestri",
          role: "CFO",
          tag: { label: "Guide", tone: "neutral" },
          timestamp: "17:02 ET",
        },
        {
          type: "quote",
          text:
            "On Apple Intelligence — we are seeing very strong engagement with the features that have rolled out. It is a multi-year journey, and I could not be more optimistic about what it means for the customer experience.",
          speaker: "Tim Cook",
          role: "CEO",
          tag: { label: "AI", tone: "positive" },
          timestamp: "17:18 ET",
        },
      ],
    },
  ],
  citations: [
    {
      id: "8k",
      title: "Form 8-K — Q2 FY26 results",
      source: "SEC EDGAR",
      url: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193",
      date: "Today",
    },
    {
      id: "press",
      title: "Apple Reports Second Quarter Results",
      source: "Apple Newsroom",
      url: "https://www.apple.com/newsroom/",
      date: "Today",
    },
    {
      id: "transcript",
      title: "Q2 FY26 earnings call transcript",
      source: "Internal capture",
      date: "Today",
    },
  ],
};

const STUB_REPORT_FOR_OTHER_DEMOS = (
  ticker: string,
  title: string,
): ReportSchema => ({
  schema_version: "2.0",
  department: "earnings_update",
  generated_at: new Date().toISOString(),
  page_furniture: {
    header: { left: "OpenLIA", right: "Earnings Update" },
    footer: {
      left: "Generated for internal use",
      center: "Page {page} of {total}",
      right: `${ticker} · Demo`,
    },
    disclaimer:
      "Demo report. Backend wiring required for the full schema; this is a placeholder body so the viewer renders.",
  },
  cover: {
    title,
    subtitle: "Demo report",
    eyebrow: `EARNINGS UPDATE · ${ticker}`,
    ticker,
    tagline:
      "This is a demo placeholder. The full report renderer is wired up; only the AAPL print has full content authored in demo mode.",
  },
  sections: [
    {
      id: "placeholder",
      title: "Placeholder",
      blocks: [
        {
          type: "text",
          content:
            "Open the AAPL print from the Today's section to see a fully authored demo report.",
        },
      ],
    },
  ],
});

const DEMO_REPORTS: Record<string, ReportSchema> = {
  "demo-aapl-q2": AAPL_REPORT,
};

export function isDemoReportId(reportId: string): boolean {
  return reportId.startsWith("demo-");
}

export function getDemoReportSchema(reportId: string): ReportSchema {
  const known = DEMO_REPORTS[reportId];
  if (known) return known;
  const ticker = reportId.replace(/^demo-/, "").split("-")[0]?.toUpperCase() ?? "DEMO";
  return STUB_REPORT_FOR_OTHER_DEMOS(ticker, `${ticker} — Demo earnings update`);
}
