"""add cached_documents

Revision ID: f3d303f0d092
Revises: 20260520_0001_report_templates
Create Date: 2026-05-21 08:06:20.038810+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3d303f0d092"
down_revision: str | Sequence[str] | None = "20260520_0001_report_templates"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_documents",
        sa.Column("cache_key", sa.String(length=512), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=256), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("fiscal_period", sa.String(length=32), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("original_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bytes_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("cache_key", name=op.f("pk_cached_documents")),
    )
    with op.batch_alter_table("cached_documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_cached_documents_ticker_fiscal", ["ticker", "fiscal_period"], unique=False
        )

    # The autogen run that produced this migration captured a stray
    # `idx_chat_sessions_attached_report_id` index from one dev DB; the
    # ORM model never defined that index, so it's absent on fresh installs
    # and the unconditional drop_index here crashes the migration. Make
    # the drop idempotent by inspecting the live DB first.
    existing_chat_sessions_indexes = {
        ix["name"] for ix in sa.inspect(op.get_bind()).get_indexes("chat_sessions")
    }
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        if "idx_chat_sessions_attached_report_id" in existing_chat_sessions_indexes:
            batch_op.drop_index(batch_op.f("idx_chat_sessions_attached_report_id"))
        batch_op.create_foreign_key(
            batch_op.f("fk_chat_sessions_attached_report_id_reports"),
            "reports",
            ["attached_report_id"],
            ["id"],
            ondelete="SET NULL",
            use_alter=True,
        )

    existing_reports_indexes = {
        ix["name"] for ix in sa.inspect(op.get_bind()).get_indexes("reports")
    }
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(), server_default=None, nullable=True
        )
        if "idx_reports_status" in existing_reports_indexes:
            batch_op.drop_index(batch_op.f("idx_reports_status"))

    with op.batch_alter_table("rs_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rs_snapshots_ticker_captured"))
        batch_op.create_index(
            "ix_rs_snapshots_ticker_captured",
            ["ticker", sa.literal_column("captured_at DESC")],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rs_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_rs_snapshots_ticker_captured")
        batch_op.create_index(
            batch_op.f("ix_rs_snapshots_ticker_captured"), ["ticker", "captured_at"], unique=False
        )

    # idx_reports_status and idx_chat_sessions_attached_report_id were
    # never created by any prior migration — the upgrade()'s drops were
    # autogen artefacts from a stray dev DB. Don't fabricate them here.
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("'complete'"),
            nullable=False,
        )

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_chat_sessions_attached_report_id_reports"), type_="foreignkey"
        )

    with op.batch_alter_table("cached_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_cached_documents_ticker_fiscal")

    op.drop_table("cached_documents")
    # ### end Alembic commands ###
