"""Resolver redesign Phase 10: make audit log spec_id nullable + non-cascading.

The save flow must persist a SmokeCallLog row even when smoke fails and
no live RunnerCallableSpec is created. Phase 1 wired the audit tables'
``spec_id`` as ``NOT NULL`` with ``ON DELETE CASCADE``, which forced
either a placeholder spec row (which would survive after a smoke
failure) or cascade-deletes the audit history. Both are wrong: we want
durable logs that can outlive the spec row.

This migration relaxes ``spec_id`` to nullable and changes the FK
ON DELETE behavior to ``SET NULL`` so deleting a spec preserves its
audit trail.

Revision ID: 20260502_0200_audit_orphan
Revises: 20260502_0100_rrd_p1
Create Date: 2026-05-02
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260502_0200_audit_orphan"
down_revision: str | Sequence[str] | None = "20260502_0100_rrd_p1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _resolver_call_log_table(*, fk_name: str, fk_ondelete: str, spec_id_nullable: bool) -> sa.Table:
    return sa.Table(
        "resolver_call_log",
        sa.MetaData(),
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "spec_id",
            sa.String(length=36),
            sa.ForeignKey(
                "runner_callable_specs.id",
                ondelete=fk_ondelete,
                name=fk_name,
            ),
            nullable=spec_id_nullable,
        ),
        sa.Column("department_id", sa.String(length=64), nullable=False),
        sa.Column("need_id", sa.String(length=64), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "status IN ('success', 'invalid_output', 'llm_error', 'timeout')",
            name="resolver_call_log_status",
        ),
    )


def _smoke_call_log_table(*, fk_name: str, fk_ondelete: str, spec_id_nullable: bool) -> sa.Table:
    return sa.Table(
        "smoke_call_log",
        sa.MetaData(),
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "spec_id",
            sa.String(length=36),
            sa.ForeignKey(
                "runner_callable_specs.id",
                ondelete=fk_ondelete,
                name=fk_name,
            ),
            nullable=spec_id_nullable,
        ),
        sa.Column("args", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "attempt",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("response_excerpt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "status IN ('success', 'auth', 'schema_miss', 'empty', 'bad_params', 'transient')",
            name="smoke_call_log_status",
        ),
    )


def upgrade() -> None:
    """Rebuild both audit tables with spec_id nullable + ON DELETE SET NULL.

    The original FKs in 20260502_0100 were declared inline without explicit
    names. SQLite's reflected name is autogenerated and not stable across
    environments, so `batch.drop_constraint("fk_...", ...)` raises
    "No such constraint" on some DBs. We bypass that with `copy_from`,
    handing batch_alter_table a fresh Table object that already has the
    desired schema; SQLite recreates the table cleanly and copies data.
    """
    target = _resolver_call_log_table(
        fk_name="fk_resolver_call_log_spec_id",
        fk_ondelete="SET NULL",
        spec_id_nullable=True,
    )
    with op.batch_alter_table("resolver_call_log", copy_from=target):
        pass

    target = _smoke_call_log_table(
        fk_name="fk_smoke_call_log_spec_id",
        fk_ondelete="SET NULL",
        spec_id_nullable=True,
    )
    with op.batch_alter_table("smoke_call_log", copy_from=target):
        pass


def downgrade() -> None:
    # Restore NOT NULL + ON DELETE CASCADE on both tables.
    target = _smoke_call_log_table(
        fk_name="fk_smoke_call_log_spec_id",
        fk_ondelete="CASCADE",
        spec_id_nullable=False,
    )
    with op.batch_alter_table("smoke_call_log", copy_from=target):
        pass

    target = _resolver_call_log_table(
        fk_name="fk_resolver_call_log_spec_id",
        fk_ondelete="CASCADE",
        spec_id_nullable=False,
    )
    with op.batch_alter_table("resolver_call_log", copy_from=target):
        pass
