"""Dashboard, scheduler, and notification tables — 11 tables added on top of the Plan 1A baseline.

Revision ID: f2a9566f7bf9
Revises: 01526cb27f5e
Create Date: 2026-04-18 16:34:00.745315+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2a9566f7bf9"
down_revision: str | Sequence[str] | None = "01526cb27f5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pt_presets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_shipped", sa.Boolean(), nullable=False),
        sa.Column("panel_config", sa.JSON(), nullable=False),
        sa.Column("composite_settings", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pt_presets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pt_presets")),
        sa.UniqueConstraint("user_id", "name", name="uq_pt_presets_user_name"),
    )
    with op.batch_alter_table("pt_presets", schema=None) as batch_op:
        batch_op.create_index(
            "uq_pt_presets_shipped_name",
            ["name"],
            unique=True,
            sqlite_where=sa.text("user_id IS NULL"),
        )

    op.create_table(
        "pt_user_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("active_preset_id", sa.String(length=36), nullable=True),
        sa.Column("panel_config", sa.JSON(), nullable=False),
        sa.Column("composite_settings", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_preset_id"],
            ["pt_presets.id"],
            name=op.f("fk_pt_user_configs_active_preset_id_pt_presets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pt_user_configs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pt_user_configs")),
        sa.UniqueConstraint("user_id", name=op.f("uq_pt_user_configs_user_id")),
    )
    op.create_table(
        "mr_dashboard_state",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("dashboard", sa.String(length=32), nullable=False),
        sa.Column("view_config", sa.JSON(), nullable=False),
        sa.Column("threshold_overrides", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mr_dashboard_state_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mr_dashboard_state")),
        sa.UniqueConstraint("user_id", "dashboard", name="uq_mr_dashboard_user_dashboard"),
    )
    op.create_table(
        "mr_assessment_cache",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dashboard", sa.String(length=32), nullable=False),
        sa.Column("assessment_type", sa.String(length=16), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("model_ref", sa.String(length=128), nullable=False),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mr_assessment_cache")),
        sa.UniqueConstraint(
            "dashboard",
            "assessment_type",
            "input_hash",
            name="uq_mr_assessment_dash_type_hash",
        ),
    )
    op.create_table(
        "rs_user_config",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("active_tab", sa.String(length=32), nullable=False),
        sa.Column("metric_settings", sa.JSON(), nullable=False),
        sa.Column("filter_presets", sa.JSON(), nullable=False),
        sa.Column("refresh_interval_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_rs_user_config_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rs_user_config")),
        sa.UniqueConstraint("user_id", name=op.f("uq_rs_user_config_user_id")),
    )
    op.create_table(
        "rs_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("snapshot_data", sa.JSON(), nullable=False),
        sa.Column("source_breakdown", sa.JSON(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rs_snapshots")),
    )
    with op.batch_alter_table("rs_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_rs_snapshots_ticker_captured", ["ticker", "captured_at"], unique=False
        )

    op.create_table(
        "fe_saved_formulas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("department_scope", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_fe_saved_formulas_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fe_saved_formulas")),
        sa.UniqueConstraint("user_id", "name", name="uq_fe_formulas_user_name"),
    )
    op.create_table(
        "mb_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("time", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("days_of_week", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mb_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mb_schedules")),
    )
    with op.batch_alter_table("mb_schedules", schema=None) as batch_op:
        batch_op.create_index("ix_mb_schedules_user", ["user_id"], unique=False)

    op.create_table(
        "eu_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("time", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("days_of_week", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_eu_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eu_schedules")),
    )
    with op.batch_alter_table("eu_schedules", schema=None) as batch_op:
        batch_op.create_index("ix_eu_schedules_user", ["user_id"], unique=False)

    op.create_table(
        "job_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("schedule_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("retry_of", sa.String(length=36), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["retry_of"],
            ["job_runs.id"],
            name=op.f("fk_job_runs_retry_of_job_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_job_runs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.create_index("ix_job_runs_schedule", ["schedule_id", "started_at"], unique=False)
        batch_op.create_index("ix_job_runs_status", ["status"], unique=False)
        batch_op.create_index(
            "ix_job_runs_user_type_started",
            ["user_id", "job_type", "started_at"],
            unique=False,
        )

    op.create_table(
        "user_notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("department", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("job_run_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
            name=op.f("fk_user_notifications_job_run_id_job_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_notifications")),
    )
    with op.batch_alter_table("user_notifications", schema=None) as batch_op:
        batch_op.create_index("ix_notifications_user_unread", ["user_id", "read_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_unread")

    op.drop_table("user_notifications")
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_job_runs_user_type_started")
        batch_op.drop_index("ix_job_runs_status")
        batch_op.drop_index("ix_job_runs_schedule")

    op.drop_table("job_runs")
    with op.batch_alter_table("eu_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_eu_schedules_user")

    op.drop_table("eu_schedules")
    with op.batch_alter_table("mb_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_mb_schedules_user")

    op.drop_table("mb_schedules")
    op.drop_table("fe_saved_formulas")
    with op.batch_alter_table("rs_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_rs_snapshots_ticker_captured")

    op.drop_table("rs_snapshots")
    op.drop_table("rs_user_config")
    op.drop_table("mr_assessment_cache")
    op.drop_table("mr_dashboard_state")
    op.drop_table("pt_user_configs")
    with op.batch_alter_table("pt_presets", schema=None) as batch_op:
        batch_op.drop_index("uq_pt_presets_shipped_name")

    op.drop_table("pt_presets")
    # ### end Alembic commands ###
