import type {
  DiplomacyPanel,
  FedPanel,
  InflationPanel,
  OilPanel,
  WagePanel,
} from "./types";

export const oilPanel: OilPanel = {
  panelId: "oil",
  num: "D1",
  title: "Oil price duration",
  subtitle: "How long Brent has held above the elevated threshold",
  pillTone: "bad",
  pillLabel: "Red · 47d streak",
  lastUpdate: "Updated 06:30",
  presetLabel: "Preset · Report defaults ▾",
  bigValue: "$48.20",
  bigValueTone: "bad",
  bigValueUnit: "BNO · Brent proxy",
  bigValueStamp: { tone: "bad", label: "Above $45.00" },
  narrative: {
    parts: [
      { kind: "text", value: "BNO has closed above your $45.00 threshold for " },
      { kind: "strong", value: "47 consecutive sessions", tone: "bad" },
      {
        kind: "text",
        value: ', above the 30-day amber line and 43 days from the 90-day "2022 playbook" mark. Daily change ',
      },
      { kind: "strong", value: "+0.4%" },
      { kind: "text", value: ". ATR(14) at " },
      { kind: "strong", value: "1.04" },
      { kind: "text", value: " — vol contained." },
    ],
  },
  chart: {
    yLabels: ["$54", "$50", "$46", "$42", "$38", "$34"],
    xLabels: ["NOV", "DEC", "JAN", "FEB", "MAR", "APR"],
    thresholdPrice: 45,
    yMin: 34,
    yMax: 54,
    streakStartIndex: 18,
    streakStartLabel: "streak start · 18 Mar",
    series: [
      37, 38, 38.5, 39, 40, 41, 42, 43, 43.5, 44, 45, 45.3, 45, 45.5, 45.8, 46.5, 47.5, 48, 48.2, 48.5, 48.8, 49,
    ],
    currentLabel: "$48.20 · today",
  },
  streak: {
    days: 47,
    targetDays: 90,
    segments: [
      { status: "amber", widthPct: 1.1, leftPct: 0 },
      { status: "red", widthPct: 32.2, leftPct: 1.1 },
      { status: "darkred", widthPct: 66.7, leftPct: 33.3 },
    ],
    markerPct: 52.2,
    foots: [
      { days: "0d", tone: "neutral", label: "green" },
      { days: "1d", tone: "neutral", label: "amber" },
      { days: "30d", tone: "bad", label: "red" },
      { days: "90d", tone: "neutral", label: "2022 trigger" },
    ],
  },
  rules: [
    {
      status: "darkred",
      formulaParts: [
        { kind: "var", value: "streak_days" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "streak_dark_red", gloss: "(90)" },
      ],
      check: "false",
      matched: false,
    },
    {
      status: "red",
      formulaParts: [
        { kind: "var", value: "streak_days" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "streak_red", gloss: "(30)" },
      ],
      check: "▶ MATCH",
      matched: true,
    },
    {
      status: "amber",
      formulaParts: [
        { kind: "var", value: "price" },
        { kind: "op", value: ">" },
        { kind: "lit", value: "price_threshold", gloss: "($45)" },
      ],
      check: "true",
      matched: false,
    },
    {
      status: "green",
      formulaParts: [{ kind: "text", value: "true" }],
      check: "fallback",
      matched: false,
    },
  ],
  params: [
    { key: "ticker", value: "BNO.US" },
    { key: "price_threshold", value: "45.00" },
    { key: "streak_amber", value: "1" },
    { key: "streak_red", value: "30" },
    { key: "streak_dark_red", value: "90" },
    { key: "history_lookback_months", value: "6" },
  ],
};

export const inflationPanel: InflationPanel = {
  panelId: "inflation",
  num: "D2",
  title: "Inflation expectations",
  subtitle: "Michigan 5Y survey · TIP slope confirmation",
  pillTone: "warn",
  pillLabel: "Amber · approaching",
  lastUpdate: "Survey 25 Apr",
  presetLabel: "Preset · Report defaults ▾",
  bigValue: "2.9%",
  bigValueTone: "warn",
  bigValueUnit: "Michigan 5Y · y/y",
  bigValueStamp: { tone: "warn", label: "+0.2pp m/m" },
  narrative: {
    parts: [
      { kind: "text", value: "Michigan 5Y at " },
      { kind: "strong", value: "2.9%", tone: "warn" },
      {
        kind: "text",
        value: " — above the 2.5% amber line, 0.1pp from red. TIP ETF up ",
      },
      { kind: "strong", value: "+1.8%" },
      { kind: "text", value: " over 30 days, slope " },
      { kind: "strong", value: "+0.04", tone: "warn" },
      {
        kind: "text",
        value: " — confirming. Expectations drifting but not unanchored.",
      },
    ],
  },
  chart: {
    bands: [
      { tone: "amber", yPct: [50, 75] },
      { tone: "red", yPct: [25, 50] },
      { tone: "dark", yPct: [0, 25] },
    ],
    thresholds: [
      { tone: "dark", level: 3.5, label: "3.5% — dark red" },
      { tone: "red", level: 3.0, label: "3.0% — red" },
      { tone: "amber", level: 2.5, label: "2.5% — amber" },
    ],
    yLabels: ["3.5", "3.0", "2.5", "2.0"],
    xLabels: ["NOV", "DEC", "JAN", "FEB", "MAR", "APR"],
    yMin: 2.0,
    yMax: 3.5,
    tipSeries: [108, 108.4, 109, 109.5, 110.4, 110.9, 111.6, 112.0, 112.4],
    michiganDots: [
      { x: 80, y: 2.4 },
      { x: 190, y: 2.5 },
      { x: 300, y: 2.6 },
      { x: 410, y: 2.7 },
      { x: 520, y: 2.85 },
      { x: 630, y: 2.9, isCurrent: true, label: "2.9%" },
    ],
    tipCurrentLabel: "TIP $112.40",
  },
  rules: [
    {
      status: "darkred",
      formulaParts: [
        { kind: "var", value: "michigan_5y" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "3.5" },
      ],
      check: "false",
      matched: false,
    },
    {
      status: "red",
      formulaParts: [
        { kind: "var", value: "michigan_5y" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "3.0" },
      ],
      check: "false · 0.1pp",
      matched: false,
    },
    {
      status: "amber",
      formulaParts: [
        { kind: "var", value: "michigan_5y" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "2.5" },
      ],
      check: "▶ MATCH",
      matched: true,
    },
    {
      status: "green",
      formulaParts: [{ kind: "text", value: "true" }],
      check: "fallback",
      matched: false,
    },
  ],
  params: [
    { key: "primary_ticker", value: "TIP.US" },
    { key: "level_amber", value: "2.5" },
    { key: "level_red", value: "3.0" },
    { key: "level_dark_red", value: "3.5" },
    { key: "slope_lookback_days", value: "30" },
    { key: "slope_threshold", value: "0.02" },
  ],
};

export const fedPanel: FedPanel = {
  panelId: "fed",
  num: "D3",
  title: "Fed language tracker",
  subtitle: "Posture detection from FOMC + Powell newsflow",
  pillTone: "bad",
  pillLabel: "Red · hawkish pivot",
  lastUpdate: "Last FOMC 30 Apr",
  presetLabel: "Preset · Report defaults ▾",
  bigQuote: '"persistent inflation"',
  narrative: {
    parts: [
      { kind: "text", value: "Detected " },
      { kind: "strong", value: "hawkish", tone: "bad" },
      { kind: "text", value: " trigger phrase in Powell's 30 Apr presser. Crisis keywords " },
      { kind: "strong", value: "not detected", tone: "ok" },
      { kind: "text", value: '. The dovish lexicon ("look through", "transitory", "patient") last appeared ' },
      { kind: "strong", value: "Feb 2024" },
      { kind: "text", value: "." },
    ],
  },
  postureTimeline: [
    { label: "MAR '23", tone: "dovish" },
    { label: "MAY '23", tone: "dovish" },
    { label: "JUL '23", tone: "neutral" },
    { label: "SEP '23", tone: "neutral" },
    { label: "DEC '24", tone: "dovish" },
    { label: "MAR '25", tone: "neutral" },
    { label: "JAN '26", tone: "hawkish" },
    { label: "APR '26", tone: "hawkish", isCurrent: true },
  ],
  headlines: [
    {
      when: "30 APR",
      time: "14:32",
      body: [
        { kind: "text", value: "Powell: Fed sees " },
        { kind: "mark", value: "persistent inflation", tone: "hawkish" },
        { kind: "text", value: ' in services, will hold restrictive rates "until we see broad evidence"' },
      ],
      source: "Reuters · FOMC Press Conference",
    },
    {
      when: "29 APR",
      time: "09:18",
      body: [
        { kind: "text", value: "Williams: Labor market remains tight, FOMC " },
        { kind: "mark", value: "concerned about inflation", tone: "hawkish" },
        { kind: "text", value: " resurgence in second half" },
      ],
      source: "Bloomberg · NY Fed",
    },
    {
      when: "28 APR",
      time: "16:05",
      body: [
        { kind: "text", value: "Daly emphasizes Fed will be " },
        { kind: "mark", value: "data dependent", tone: "neutral" },
        { kind: "text", value: " through summer, downplays cut path" },
      ],
      source: "CNBC · SF Fed",
    },
    {
      when: "26 APR",
      time: "11:40",
      body: [
        { kind: "text", value: "Waller: FOMC " },
        { kind: "mark", value: "monitoring closely", tone: "neutral" },
        { kind: "text", value: " for signs that progress on inflation has stalled" },
      ],
      source: "WSJ · Federal Reserve Board",
    },
    {
      when: "22 APR",
      time: "08:55",
      body: [
        { kind: "text", value: 'Goolsbee strikes cautious tone — "We are ' },
        { kind: "mark", value: "data dependent", tone: "neutral" },
        { kind: "text", value: ', not pre-committed"' },
      ],
      source: "FT · Chicago Fed",
    },
  ],
  keywords: {
    dovish: {
      matches: [],
      standard: ["look through", "transitory", "patient", "well anchored"],
    },
    neutral: {
      matches: [],
      standard: ["monitoring closely", "data dependent", "act as appropriate"],
    },
    hawkish: {
      matches: ["persistent inflation", "concerned about inflation"],
      standard: ["broadly-based price pressures"],
    },
    crisis: {
      matches: [],
      standard: ["unanchored", "emergency", "expedited"],
    },
  },
  meta: { newsLookbackDays: 30, daysSinceFomc: 4 },
  rules: [
    {
      status: "red",
      formulaParts: [
        { kind: "var", value: "hawkish_match_count" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "1" },
      ],
      check: "▶ MATCH · 2",
      matched: true,
    },
    {
      status: "amber",
      formulaParts: [
        { kind: "var", value: "neutral_match_count" },
        { kind: "op", value: ">" },
        { kind: "lit", value: "dovish_match_count" },
      ],
      check: "true",
      matched: false,
    },
    {
      status: "green",
      formulaParts: [{ kind: "text", value: "true" }],
      check: "fallback",
      matched: false,
    },
  ],
  params: [
    { key: "force_status", value: "— auto —" },
    { key: "news_lookback_days", value: "30" },
    { key: "days_since_fomc", value: "4" },
  ],
};

export const wagePanel: WagePanel = {
  panelId: "wage",
  num: "D4",
  title: "Wage growth (Average Hourly Earnings)",
  subtitle: "Two consecutive months above threshold = spiral risk",
  pillTone: "darkred",
  pillLabel: "Dark red · 2 consecutive",
  lastUpdate: "BLS 02 May",
  presetLabel: "Preset · Report defaults ▾",
  bigValue: "+0.6%",
  bigValueUnit: "AHE · MoM",
  bigValueStamp: { tone: "darkred", label: "2nd consecutive hot print" },
  narrative: {
    parts: [
      { kind: "text", value: "April AHE printed " },
      { kind: "strong", value: "+0.6% MoM", tone: "bad" },
      { kind: "text", value: " for the second consecutive month — triggering the wage-price spiral rule. 12-month average " },
      { kind: "strong", value: "0.38%" },
      { kind: "text", value: ". Real earnings (AHE − CPI MoM) at " },
      { kind: "strong", value: "+0.27%", tone: "warn" },
      { kind: "text", value: " — wages outpacing prices." },
    ],
  },
  bars: [
    { month: "MAY", value: 0.2, status: "green" },
    { month: "JUN", value: 0.3, status: "green" },
    { month: "JUL", value: 0.3, status: "green" },
    { month: "AUG", value: 0.4, status: "amber" },
    { month: "SEP", value: 0.35, status: "green" },
    { month: "OCT", value: 0.4, status: "amber" },
    { month: "NOV", value: 0.45, status: "amber" },
    { month: "DEC", value: 0.5, status: "amber" },
    { month: "JAN", value: 0.45, status: "amber" },
    { month: "FEB", value: 0.45, status: "amber" },
    { month: "MAR", value: 0.6, status: "darkred", isCurrent: false },
    { month: "APR", value: 0.6, status: "darkred", isCurrent: true },
  ],
  thresholds: { amber: 0.4, red: 0.5 },
  yMax: 0.8,
  consecutiveBracket: { startIndex: 10, endIndex: 11, label: "2 consecutive · spiral" },
  rules: [
    {
      status: "darkred",
      formulaParts: [
        { kind: "var", value: "consecutive_count" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "2" },
      ],
      check: "▶ MATCH",
      matched: true,
    },
    {
      status: "red",
      formulaParts: [
        { kind: "var", value: "value" },
        { kind: "op", value: ">" },
        { kind: "lit", value: "wage_threshold_red", gloss: "(0.5)" },
      ],
      check: "true",
      matched: false,
    },
    {
      status: "amber",
      formulaParts: [
        { kind: "var", value: "value" },
        { kind: "op", value: ">" },
        { kind: "lit", value: "wage_threshold_amber", gloss: "(0.4)" },
      ],
      check: "true",
      matched: false,
    },
    {
      status: "green",
      formulaParts: [{ kind: "text", value: "true" }],
      check: "fallback",
      matched: false,
    },
  ],
  params: [
    { key: "wage_threshold_amber", value: "0.4" },
    { key: "wage_threshold_red", value: "0.5" },
    { key: "consecutive_required", value: "2" },
    { key: "history_lookback_months", value: "12" },
    { key: "cpi_mom (latest)", value: "0.33" },
    { key: "avg_12m", value: "0.38" },
  ],
};

export const diplomacyPanel: DiplomacyPanel = {
  panelId: "diplomacy",
  num: "D5",
  title: "Diplomatic progress",
  subtitle: "Rolling milestone window with news support",
  pillTone: "warn",
  pillLabel: "Amber · 22/30 days elapsed",
  lastUpdate: "Last milestone 11 Apr",
  presetLabel: "Preset · Report defaults ▾",
  countdown: {
    elapsed: 22,
    total: 30,
    remaining: 8,
    progressPct: 73.3,
    startLabel: "Day 0 · 11 Apr · ceasefire framework signed",
    endLabel: "Day 30 · 11 May · window closes",
  },
  signals: { progress: 3, escalation: 0 },
  headlines: [
    {
      when: "02 MAY",
      time: "06:14",
      body: [
        { kind: "text", value: "Riyadh hosts Iran-GCC " },
        { kind: "mark", value: "de-escalation", tone: "dovish" },
        { kind: "text", value: " talks; communiqué due Wed" },
      ],
      source: "FT · Middle East",
    },
    {
      when: "29 APR",
      time: "22:08",
      body: [
        { kind: "text", value: "Hormuz traffic returns to baseline; Iran lifts " },
        { kind: "mark", value: "ceasefire", tone: "dovish" },
        { kind: "text", value: "-related insurance levy" },
      ],
      source: "Reuters · Energy",
    },
    {
      when: "26 APR",
      time: "13:51",
      body: [
        { kind: "text", value: "Qatari mediation enters fourth round of " },
        { kind: "mark", value: "peace talks", tone: "dovish" },
        { kind: "text", value: '; framework "extended verbally" — sources' },
      ],
      source: "Bloomberg",
    },
    {
      when: "21 APR",
      time: "09:30",
      body: [
        { kind: "text", value: "UN envoy: phase-2 " },
        { kind: "mark", value: "negotiations", tone: "dovish" },
        { kind: "text", value: " on track despite missed signing date" },
      ],
      source: "Al Jazeera",
    },
    {
      when: "14 APR",
      time: "17:42",
      body: [
        { kind: "text", value: "Tehran central bank statement omits prior week's " },
        { kind: "mark", value: "strait", tone: "neutral" },
        { kind: "text", value: " contingency language" },
      ],
      source: "WSJ · MENA",
    },
  ],
  rules: [
    {
      status: "red",
      formulaParts: [
        { kind: "var", value: "days_elapsed" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "30" },
        { kind: "op", value: "AND" },
        { kind: "var", value: "escalation_detected" },
      ],
      check: "false / false",
      matched: false,
    },
    {
      status: "red",
      formulaParts: [
        { kind: "var", value: "days_elapsed" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "window_days", gloss: "(30)" },
      ],
      check: "false · 22",
      matched: false,
    },
    {
      status: "amber",
      formulaParts: [
        { kind: "var", value: "days_elapsed" },
        { kind: "op", value: ">=" },
        { kind: "lit", value: "window_days" },
        { kind: "op", value: "×" },
        { kind: "lit", value: "0.5" },
      ],
      check: "▶ MATCH · 22 ≥ 15",
      matched: true,
    },
    {
      status: "green",
      formulaParts: [{ kind: "text", value: "true" }],
      check: "fallback",
      matched: false,
    },
  ],
  params: [
    { key: "window_days", value: "30" },
    { key: "window_amber_pct", value: "50" },
    { key: "milestone_date", value: "2026-04-11" },
    { key: "news_lookback_days", value: "30" },
  ],
};
