import type { ReleaseRow } from "./types";

export const releaseRows: ReleaseRow[] = [
  {
    whenDay: "FRI 02 MAY",
    whenTime: "08:30 ET",
    name: "Average Hourly Earnings MoM",
    source: "BLS · Apr",
    actual: "+0.6%",
    actualTone: "neg",
    consensus: "+0.4%",
    prior: "+0.6%",
    surprise: "+0.2pp",
    surpriseTone: "neg",
    surpriseTag: "hot",
  },
  {
    whenDay: "FRI 02 MAY",
    whenTime: "08:30 ET",
    name: "Nonfarm Payrolls",
    source: "BLS · Apr",
    actual: "242k",
    actualTone: "warn",
    consensus: "220k",
    prior: "228k",
    surprise: "+22k",
    surpriseTone: "warn",
    surpriseTag: "hot",
  },
  {
    whenDay: "WED 30 APR",
    whenTime: "14:00 ET",
    name: "FOMC Decision & Statement",
    source: "Federal Reserve · May",
    actual: "5.25–5.50%",
    actualTone: "neutral",
    consensus: "5.25–5.50%",
    prior: "5.25–5.50%",
    surprise: "hawkish",
    surpriseTone: "neg",
    surpriseTag: "tone",
  },
  {
    whenDay: "WED 30 APR",
    whenTime: "08:30 ET",
    name: "Core PCE y/y",
    source: "BEA · Mar",
    actual: "2.9%",
    actualTone: "warn",
    consensus: "2.7%",
    prior: "2.8%",
    surprise: "+0.2pp",
    surpriseTone: "warn",
    surpriseTag: "hot",
  },
  {
    whenDay: "FRI 25 APR",
    whenTime: "10:00 ET",
    name: "Michigan 5Y Inflation Expectations",
    source: "UMich · Apr final",
    actual: "2.9%",
    actualTone: "warn",
    consensus: "2.8%",
    prior: "2.85%",
    surprise: "+0.1pp",
    surpriseTone: "warn",
    surpriseTag: "up",
  },
  {
    whenDay: "THU 24 APR",
    whenTime: "08:30 ET",
    name: "Real Earnings MoM",
    source: "BLS · Mar",
    actual: "+0.27%",
    actualTone: "warn",
    consensus: "+0.15%",
    prior: "+0.20%",
    surprise: "+0.12pp",
    surpriseTone: "warn",
  },
  {
    whenDay: "WED 23 APR",
    whenTime: "08:30 ET",
    name: "CPI MoM",
    source: "BLS · Mar",
    actual: "+0.33%",
    actualTone: "pos",
    consensus: "+0.30%",
    prior: "+0.38%",
    surprise: "−0.05pp",
    surpriseTone: "pos",
  },
];
